### ISSUE TITLE
Escopo e tarefas 

### ISSUE THREAD

**Issue by lucasrcoutinho** [adrianomunin/Sistema-Operacionais-B#1]
- [x] Definição do sistema e versão que será utilizado 
- [x] Compilar uma versão do kernel para validar o procedimento  
- [x] Definir quais componentes e módulos estão sendo utilizados pela maquina virtual
- [x] Testar versões do kernel removendo alguns módulos
- [x] Depurar possíveis erros de compilação ou execução 
- [x] Compilar uma versão final com minimo possível de módulos e componentes
- [x] Elaboração do relatório com as conclusões obtidas durante a execução do projeto

**Comment by lucasrcoutinho** [comment]
Foi instalada com sucesso uma versão do kernel 5.0.0 completo (sem alterações), assim o procedimento de compilação e instalação está validado!

**Comment by lucasrcoutinho** [comment]
Caso eu tenha me esquecido de adicionar algo, ou queiram alterar algum tópico, fiquem à vontade em editar.

**Comment by iaglourenco** [comment]
Quem usa VM posta aqui um `cat` do `lspci -v` da VM pra ver os módulos usados por cada dispositivo e um outro `cat` do `lsmod` para ver os módulos carregados. Pode ser em um arquivo .txt
